Ext.define("vmd.ux.DevelopServerInfo" ,{
	extend:"Ext.Panel",
	requires:vmd.getCmpDeps([]),
	version:"1.0",
	xtype:"vmd.ux.DevelopServerInfo",
	title:"Panel",
	header:false,
	border:false,
	width:684,
	height:365,
	layout:"absolute",
	bodyStyle:"font-size:14px;",
	initComponent: function(){
		function resetCmpScope() {
                    var cmpList = me._reloadCmpList;
                    Ext.each(cmpList, function (name) {
                        var cmpObj = eval(name);
                        cmpObj && (cmpObj._beforeRender = function (_cmp) {
                            var id = vmd.core.getCmpId(_cmp);
                            id&&eval(id + "= _cmp")
                        })
                    })
                }
			
			this.items=[
			{
				xtype:"label",
				id:"label",
				text:"数据服务：",
				x:20,
				y:30
			},
			{
				xtype:"label",
				id:"label1",
				text:"流程中心：",
				x:20,
				y:70
			},
			{
				xtype:"label",
				id:"label2",
				text:"消息中心：",
				x:20,
				y:110
			},
			{
				xtype:"label",
				id:"label3",
				text:"待办中心：",
				x:20,
				y:150
			},
			{
				xtype:"label",
				id:"label4",
				text:"认证中心：",
				x:20,
				y:190
			},
			{
				xtype:"label",
				id:"label5",
				text:"文档中心：",
				x:20,
				y:230
			},
			{
				xtype:"label",
				id:"label6",
				text:"报表中心：",
				x:20,
				y:270
			},
			{
				xtype:"label",
				id:"label7",
				text:"日志中心：",
				x:20,
				y:310
			},
			{
				xtype:"textfield",
				id:"hwText",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:30,
				width:350
			},
			{
				xtype:"textfield",
				id:"hwText1",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:70,
				width:350
			},
			{
				xtype:"textfield",
				id:"hwText2",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:110,
				width:350
			},
			{
				xtype:"textfield",
				id:"hwText3",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:150,
				width:350
			},
			{
				xtype:"textfield",
				id:"hwText4",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:190,
				width:350
			},
			{
				xtype:"textfield",
				id:"hwText5",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:230,
				width:350
			},
			{
				xtype:"textfield",
				id:"hwText6",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:270,
				width:350
			},
			{
				xtype:"textfield",
				id:"hwText7",
				allowBlank:true,
				enableKeyEvents:true,
				x:90,
				y:310,
				width:350
			}
		]
		this.callParent();
		vmd.core.compositeCmpInit(this.items, this);
		var me = this;eval(me.defineVars);
		resetCmpScope();
		Ext.util.CSS.removeStyleSheet("vmd.ux.DevelopServerInfo");
		this.uxCss&&Ext.util.CSS.createStyleSheet(vmd.replaceResVars(this.uxCss), "vmd.ux.DevelopServerInfo");
	}
})