Ext.define("vmd.ux.RptProperty" ,{
	extend:"Ext.Panel",
	requires:vmd.getCmpDeps(["vmd.ux.TextTypeProperty$1.0$TextTypeProperty","vmd.ux.ComboBoxProperty$1.0$ComboBoxProperty"]),
	version:"1.0",
	xtype:"vmd.ux.RptProperty",
	title:"Panel",
	header:false,
	border:false,
	width:480,
	height:760,
	layout:"fit",
	autoScroll:false,
	initComponent: function(){
		var store = new Ext.data.JsonStore({
    proxy: new Ext.data.MemoryProxy(),
    fields: ['id', 'name']
});
var data = [{
    id: 'text',
    name: '文本'
}, {
    id: 'combobox',
    name: '下拉框'
}]
store.loadData(data);

function type_panel_afterrender(sender) {
    cmbType.store = store;
    cmbType.displayField = 'name';
    cmbType.valueField = 'id'

}

function cmbType_change(sender) {
    if(cmbType.getValue() == "text") {
        TextTypeProperty.show();
        ComboBoxProperty.hide();
    } else {
        TextTypeProperty.hide();
        ComboBoxProperty.show();
    }
}
			this.items=[
			{
				xtype:"tabpanel",
				id:"MyTabs",
				activeTab:3,
				height:710,
				width:470,
				x:-5,
				y:0,
				activeItem:"content_panel",
				items:[
					{
						xtype:"panel",
						id:"content_panel",
						title:"内容",
						header:true,
						border:true,
						height:100,
						layout:"absolute",
						items:[
							{
								xtype:"label",
								id:"label",
								text:"实际值：",
								x:20,
								y:20
							},
							{
								xtype:"label",
								id:"label1",
								text:"显示值：",
								x:20,
								y:60
							},
							{
								xtype:"textfield",
								id:"actrulValue_txt",
								allowBlank:true,
								x:76,
								y:18,
								width:270
							},
							{
								xtype:"textfield",
								id:"showValue_txt",
								allowBlank:true,
								x:76,
								y:58,
								width:270
							},
							{
								xtype:"label",
								id:"label2",
								text:"条件属性：",
								x:20,
								y:110,
								height:20
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox",
								fieldLabel:"Checkbox",
								boxLabel:"背景色",
								x:40,
								y:140
							},
							{
								xtype:"textfield",
								id:"hwText",
								allowBlank:true,
								x:120,
								y:140,
								readOnly:false,
								disabled:false,
								hidden:false,
								width:230
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox1",
								fieldLabel:"Checkbox",
								boxLabel:"前景色",
								x:40,
								y:180
							},
							{
								xtype:"textfield",
								id:"hwText1",
								allowBlank:true,
								x:120,
								y:180,
								width:230
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox2",
								fieldLabel:"Checkbox",
								boxLabel:"左缩进",
								x:40,
								y:220
							},
							{
								xtype:"textfield",
								id:"hwText2",
								allowBlank:true,
								x:120,
								y:220,
								width:230
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox3",
								fieldLabel:"Checkbox",
								boxLabel:"行字体",
								x:40,
								y:260
							},
							{
								xtype:"textfield",
								id:"hwText3",
								allowBlank:true,
								x:120,
								y:260,
								width:230
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox4",
								fieldLabel:"Checkbox",
								boxLabel:"宽度",
								x:40,
								y:300
							},
							{
								xtype:"textfield",
								id:"hwText4",
								allowBlank:true,
								x:120,
								y:300,
								width:230
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox5",
								fieldLabel:"Checkbox",
								boxLabel:"可用",
								x:40,
								y:340
							},
							{
								xtype:"textfield",
								id:"hwText5",
								allowBlank:true,
								x:120,
								y:340,
								width:230
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox6",
								fieldLabel:"Checkbox",
								boxLabel:"高度",
								x:40,
								y:380
							},
							{
								xtype:"textfield",
								id:"hwText6",
								allowBlank:true,
								x:120,
								y:380,
								width:230
							},
							{
								xtype:"label",
								id:"label3",
								text:"合并：",
								x:20,
								y:420
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox7",
								fieldLabel:"Checkbox",
								boxLabel:"同值向下合并",
								x:40,
								y:450
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox8",
								fieldLabel:"Checkbox",
								boxLabel:"同值向右合并",
								x:40,
								y:490
							},
							{
								xtype:"label",
								id:"label4",
								text:"依赖条件：",
								x:160,
								y:454,
								height:20
							},
							{
								xtype:"textfield",
								id:"hwText7",
								allowBlank:true,
								x:230,
								y:450,
								width:120
							},
							{
								xtype:"label",
								id:"label5",
								text:"依赖条件：",
								x:160,
								y:494
							},
							{
								xtype:"textfield",
								id:"hwText8",
								allowBlank:true,
								x:230,
								y:490,
								width:120
							},
							{
								xtype:"vmd.button",
								id:"button",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:20,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button1",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:60,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button2",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:140,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button3",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:180,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button4",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:220,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button5",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:260,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button6",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:300,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button7",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:340,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button8",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:380,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button9",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:450,
								width:30
							},
							{
								xtype:"vmd.button",
								id:"button10",
								text:"...",
								type:"(none)",
								size:"mini",
								x:350,
								y:490,
								width:30
							}
						]
					},
					{
						xtype:"panel",
						id:"type_panel",
						title:"类型",
						header:true,
						border:true,
						height:605,
						layout:"absolute",
						afterrender:"type_panel_afterrender",
						width:458,
						autoScroll:true,
						listeners:{
							afterrender:type_panel_afterrender
						},
						items:[
							{
								xtype:"vmd.combo",
								id:"cmbType",
								width:228,
								x:90,
								y:15,
								change:"cmbType_change",
								firstSelected:true,
								listeners:{
									change:cmbType_change
								}
							},
							{
								xtype:"label",
								id:"label6",
								text:"类型：",
								x:40,
								y:20
							},
							{
								xtype:"vmd.ux.TextTypeProperty",
								id:"TextTypeProperty",
								chkEdit:true,
								chkPrint:true,
								x:20,
								y:70,
								height:520,
								chkSymbol:false,
								chkMulti:false
							},
							{
								xtype:"vmd.ux.ComboBoxProperty",
								id:"ComboBoxProperty",
								x:5,
								y:50,
								width:460,
								height:660
							}
						]
					},
					{
						xtype:"panel",
						id:"extra_panel",
						title:"扩展",
						header:true,
						border:true,
						height:100,
						layout:"absolute",
						items:[
							{
								xtype:"label",
								id:"label7",
								text:"左父格：",
								x:20,
								y:20
							},
							{
								xtype:"textfield",
								id:"hwText9",
								allowBlank:true,
								x:80,
								y:18
							},
							{
								xtype:"vmd.button",
								id:"button11",
								text:"...",
								type:"(none)",
								size:"mini",
								x:230,
								y:20,
								width:30
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox9",
								fieldLabel:"Checkbox",
								boxLabel:"清楚左父格",
								x:80,
								y:50,
								checked:true
							},
							{
								xtype:"label",
								id:"label8",
								text:"上父格：",
								x:20,
								y:80
							},
							{
								xtype:"textfield",
								id:"hwText10",
								allowBlank:true,
								x:80,
								y:80
							},
							{
								xtype:"vmd.button",
								id:"button12",
								text:"...",
								type:"(none)",
								size:"mini",
								x:230,
								y:80,
								width:30
							},
							{
								xtype:"checkbox",
								id:"hwCheckbox10",
								fieldLabel:"Checkbox",
								boxLabel:"清楚上父格",
								x:80,
								y:112,
								checked:true
							},
							{
								xtype:"label",
								id:"label9",
								text:"扩展方向：",
								x:10,
								y:150
							}
						]
					},
					{
						xtype:"panel",
						id:"style_panel",
						title:"样式",
						header:true,
						border:true,
						height:100
					},
					{
						xtype:"panel",
						id:"other_panel",
						title:"其他",
						header:true,
						border:true,
						height:100
					}
				]
			}
		]
		this.callParent();
		vmd.core.compositeCmpInit(this.items, this);
		var me = this;eval(me.defineVars);
		Ext.util.CSS.removeStyleSheet("vmd.ux.RptProperty");
		this.uxCss&&Ext.util.CSS.createStyleSheet(this.uxCss, "vmd.ux.RptProperty");
	}
})