// 柱形开采指标字段配置文件
Vmd.define('hwchart.config.columnIndexData', {
    requires: []
}, function () {
    hwchart.config.columnIndexData = {
        jh:'id',
            ly:{
                name:'累产油',
                shortName:'LCY',
                company:'万T',
                color:'rgb(255,0,0)'
            },
            ls:{
                name:'累产水',
                shortName:'LCS',
                company:'万T',
                color:'rgb(0,0,255)'
            },
            lq:{
                name:'累产气',
                shortName:'LCQ',
                company:'万T',
                color:'rgb(255,153,0)'
            },
            cy:{
                name:'日产油',
                shortName:'RCY',
                company:'T',
                color:'rgb(163,73,164)'
            },
            cs:{
                name:'日产水',
                shortName:'RCS',
                company:'T',
                color:'rgb(0,0,200)'
            },
            cq:{
                name:'日产气',
                shortName:'RCQ',
                company:'T',
                color:'rgb(255,255,0)'
            },
            lzs:{
                name:'累注水',
                shortName:'LZS',
                company:'万T',
                color:'rgb(0,255,0)'
            },
            rzs:{
                name:'日注水',
                shortName:'RCS',
                company:'Tt',
                color:'rgb(0,255,255)'
            },
            wd:{
                name:'温度',
                shortName:'C',
                company:'',
                color:'rgb(0,255,255)'
            },
            yl:{
                name:'压力',
                shortName:'Q',
                company:'Mpa',
                color:'rgb(0,255,255)'
            },
    };
});