Ext.define("vmd.ux.TextTypeProperty" ,{
	extend:"Ext.Panel",
	requires:vmd.getCmpDeps([]),
	version:'1.0',
	xtype:"vmd.ux.TextTypeProperty",
	title:"Panel",
	header:false,
	border:false,
	width:407,
	height:590,
	layout:"absolute",
	chkEdit:true,
	chkPrint:true,
	initComponent: function(){
		
			this.items=[
			{
				xtype:"checkbox",
				id:"hwCheckbox",
				fieldLabel:"Checkbox",
				boxLabel:"允许编辑",
				x:20,
				y:20,
				checked:this.chkEdit
			},
			{
				xtype:"checkbox",
				id:"hwCheckbox1",
				fieldLabel:"Checkbox",
				boxLabel:"允许打印",
				x:20,
				y:50,
				checked:this.chkPrint
			},
			{
				xtype:"checkbox",
				id:"hwCheckbox2",
				fieldLabel:"Checkbox",
				boxLabel:"支持多行",
				x:20,
				y:80,
				checked:this.chkMulti
			},
			{
				xtype:"checkbox",
				id:"hwCheckbox3",
				fieldLabel:"Checkbox",
				boxLabel:"符号",
				x:20,
				y:110,
				checked:this.chkSymbol
			},
			{
				xtype:"textfield",
				id:"hwText",
				allowBlank:true,
				x:100,
				y:110,
				width:180,
				emptyText:this.txtSymbol
			},
			{
				xtype:"vmd.button",
				id:"button",
				text:"...",
				type:"(none)",
				size:"mini",
				x:280,
				y:110,
				width:30
			},
			{
				xtype:"label",
				id:"label",
				text:"注：用于添加键盘上没有的特殊符号；可以使数据库字段信息，也可以是自定义符号，用（，）逗号隔开",
				x:30,
				y:140,
				height:40,
				width:290
			},
			{
				xtype:"label",
				id:"label1",
				text:"校验",
				x:20,
				y:190
			},
			{
				xtype:"checkbox",
				id:"hwCheckbox4",
				fieldLabel:"Checkbox",
				boxLabel:"允许为空",
				x:30,
				y:220,
				checked:true
			},
			{
				xtype:"label",
				id:"label2",
				text:"提示信息：",
				x:120,
				y:224
			},
			{
				xtype:"textfield",
				id:"hwText1",
				allowBlank:true,
				x:190,
				y:220
			},
			{
				xtype:"label",
				id:"label3",
				text:"填写规则：",
				x:30,
				y:266,
				height:20
			},
			{
				xtype:"vmd.combo",
				id:"combo",
				width:238,
				x:100,
				y:260
			}
		]
		this.callParent();
		vmd.core.compositeCmpInit(this.items, this);
		var me = this;eval(me.defineVars);
	}
})