Ext.define("vmd.ux.PublishServerInfo" ,{
	extend:"Ext.Panel",
	requires:vmd.getCmpDeps([]),
	version:"1.0",
	xtype:"vmd.ux.PublishServerInfo",
	title:"Panel",
	header:false,
	border:false,
	width:600,
	height:388,
	layout:"fit",
	bodyStyle:"font-size:14px;",
	initComponent: function(){
		function resetCmpScope() {
                    var cmpList = me._reloadCmpList;
                    Ext.each(cmpList, function (name) {
                        var cmpObj = eval(name);
                        cmpObj && (cmpObj._beforeRender = function (_cmp) {
                            var id = vmd.core.getCmpId(_cmp);
                            id&&eval(id + "= _cmp")
                        })
                    })
                }
			
			this.items=[
			{
				xtype:"vmd.div",
				id:"div2",
				autoEl:"div",
				border:false,
				backgroundRepeat:"no-repeat",
				backgroundPosition:"top left",
				width:400,
				height:50,
				layout:"border",
				items:[
					{
						xtype:"vmd.div",
						id:"div1",
						autoEl:"div",
						border:false,
						backgroundRepeat:"no-repeat",
						backgroundPosition:"top left",
						width:455,
						height:40,
						x:0,
						y:0,
						layout:"absolute",
						style:"border-bottom: 1px solid #dddddd;",
						region:"north",
						items:[
							{
								xtype:"vmd.button",
								id:"button1",
								text:"从平台提取",
								type:"text",
								size:"small",
								x:350,
								y:15
							},
							{
								xtype:"label",
								id:"label8",
								text:"发布服务1：",
								x:10,
								y:15,
								style:"font-weight: bold;"
							}
						]
					},
					{
						xtype:"vmd.div",
						id:"div",
						autoEl:"div",
						border:false,
						backgroundRepeat:"no-repeat",
						backgroundPosition:"top left",
						height:341,
						layout:"absolute",
						region:"center",
						items:[
							{
								xtype:"textfield",
								id:"hwText7",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:300,
								width:300
							},
							{
								xtype:"textfield",
								id:"hwText6",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:260,
								width:300
							},
							{
								xtype:"textfield",
								id:"hwText5",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:220,
								width:300
							},
							{
								xtype:"textfield",
								id:"hwText4",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:180,
								width:300
							},
							{
								xtype:"textfield",
								id:"hwText3",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:140,
								width:300
							},
							{
								xtype:"textfield",
								id:"hwText2",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:100,
								width:300
							},
							{
								xtype:"textfield",
								id:"hwText1",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:60,
								width:300
							},
							{
								xtype:"textfield",
								id:"hwText",
								allowBlank:true,
								enableKeyEvents:true,
								x:120,
								y:20,
								width:300
							},
							{
								xtype:"label",
								id:"label7",
								text:"日志中心：",
								x:50,
								y:300,
								height:30
							},
							{
								xtype:"label",
								id:"label6",
								text:"报表中心：",
								x:50,
								y:260
							},
							{
								xtype:"label",
								id:"label5",
								text:"文档中心：",
								x:50,
								y:220
							},
							{
								xtype:"label",
								id:"label4",
								text:"认证中心：",
								x:50,
								y:180
							},
							{
								xtype:"label",
								id:"label3",
								text:"待办中心：",
								x:50,
								y:140
							},
							{
								xtype:"label",
								id:"label2",
								text:"消息中心：",
								x:50,
								y:100
							},
							{
								xtype:"label",
								id:"label1",
								text:"流程中心：",
								x:50,
								y:60
							},
							{
								xtype:"label",
								id:"label",
								text:"数据服务：",
								x:50,
								y:20
							}
						]
					}
				]
			}
		]
		this.callParent();
		vmd.core.compositeCmpInit(this.items, this);
		var me = this;eval(me.defineVars);
		resetCmpScope();
		Ext.util.CSS.removeStyleSheet("vmd.ux.PublishServerInfo");
		this.uxCss&&Ext.util.CSS.createStyleSheet(vmd.replaceResVars(this.uxCss), "vmd.ux.PublishServerInfo");
	}
})